### ISSUE TITLE
Adapter should read encoding from connection settings rather than from ActiveRecord::Base

### ISSUE THREAD

**Issue by vipantonio** [FabioMR/firebird_adapter#10]
I'm using 2 databases.

1. 1st is mysql with default encoding utf8
2. 2nd is firebird with default encoding 'ISO-8859-13'.

Adapter from 1.0.7 version runs `sql.encode` using wrong encoding (it reads it from 1st database rather than from connection).

You should fix this by using @connection.encoding rather than `encoding`

https://github.com/FabioMR/firebird_adapter/blob/3bced38782b8b8871cd90436957d96968fb75221/lib/active_record/connection_adapters/firebird/database_statements.rb#L20

https://github.com/FabioMR/firebird_adapter/blob/3bced38782b8b8871cd90436957d96968fb75221/lib/active_record/connection_adapters/firebird/database_statements.rb#L30

**Comment by FabioMR** [comment]
Thanks, I'll test this change as soon as possible!

**Comment by FabioMR** [comment]
Done. I'm closing the issue!
