### ISSUE TITLE
Ruby 2.3 and 2.4 is not supported with version 1.0.7

### ISSUE THREAD

**Issue by vipantonio** [FabioMR/firebird_adapter#11]
Using ruby 2.3 or 2.4 and trying to `bin/rails c` gets the following error:

> 
> /Users/antanas/.asdf/installs/ruby/2.4.6/lib/ruby/gems/2.4.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `require': /Users/antanas/.asdf/installs/ruby/2.4.6/lib/ruby/gems/2.4.0/gems/firebird_adapter-1.0.7/lib/active_record/connection_adapters/firebird/database_statements.rb:52: syntax error, unexpected keyword_rescue, expecting keyword_end
>       rescue Exception => e
>             ^
> /Users/antanas/.asdf/installs/ruby/2.4.6/lib/ruby/gems/2.4.0/gems/firebird_adapter-1.0.7/lib/active_record/connection_adapters/firebird/database_statements.rb:56: syntax error, unexpected keyword_end, expecting end-of-input
>   end
>      ^ (SyntaxError)

however, ruby 2.5 and 2.6 is fine 😄

**Comment by FabioMR** [comment]
Thanks @vipantonio. I've just released a new version with this fix.
