### ISSUE TITLE
firebird_adapter  is related to activerecord-fb-adapter ?

### ISSUE THREAD

**Issue by mariuz** [FabioMR/firebird_adapter#2]
Hello just one question firebird_adapter is related to activerecord-fb-adapter

https://github.com/rowland/activerecord-fb-adapter

**Comment by FabioMR** [comment]
Hello @mariuz, I used to use activerecord-fb-adapter. But it got out of date, I've tried to fix it for Rails 5 with no success.
Then I've decided to create a new gem for a customer that still use firebird.

**Comment by mariuz** [comment]
ok thank you
