### ISSUE TITLE
Is this gem not compatible with Rails 5.0?

### ISSUE THREAD

**Issue by vizcay** [FabioMR/firebird_adapter#25]
Hello Fabio! I have a legacy Rails 4.2 app that was using https://github.com/rowland/activerecord-fb-adapter. We are looking to upgrade to Rails 5 and your fork looks like the more mature one.

What I found strange is that this gem first version requires at least Rails 5.1 instead of 5.0. There was some strong reason for that or that you just started with Rails 5.1 when forking?

Our plan is to migrate to 5.1 eventually but as usual upgrading one version at the time is easier.

Thanks for your work =)

**Comment by FabioMR** [comment]
Hello @vizcay,

There was no special reason, I've just started with Rails  5.1.
I have been using the gem in production with many projects and it works well.
You can fork it and try with Rails 5.0. I suppose it will work well.

**Comment by vizcay** [comment]
For anyone interested, the API is not the same for 5.0. I've tried for a while patching the missing methods from https://github.com/rowland/activerecord-fb-adapter but I desisted when it got too ugly.
