### ISSUE TITLE
Rails 6 support

### ISSUE THREAD

**Issue by vipantonio** [FabioMR/firebird_adapter#26]
Fabio, any plans for support for Rails 6.0?

this is the only gem that works like a charm! It would be very nice to have it working in Rails 6...

the fork https://github.com/rails-firebird/ar_firebird_adapter of your gem was promising, but still not working in Rails 6 as expected...

**Comment by FabioMR** [comment]
@vipantonio I do have plans for support Rails 6.0. But unfortunately I can't say when.
I have some projects with Rails 5.2 and at some point I will need to update.

**Comment by FabioMR** [comment]
@vipantonio Now it supports Rails 6.0!
