### ISSUE TITLE
SyntaxError at database_statements.rb

### ISSUE THREAD

**Issue by luisfoxi** [FabioMR/firebird_adapter#5]
Hi!

I recived an error message during db:migrate

rails aborted!
SyntaxError: C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/firebird_adapter-1.0.2/lib/active_record/connection_adapters/firebird/database_statements.rb:30: syntax error, unexpected keyword_rescue, expecting keyword_end
      rescue => e
            ^
I solved this problem inserting begin command after line 15
     
` ActiveSupport::Dependencies.interlock.permit_concurrent_loads do`
`        begin`

 and inserting end command after line 32

`          raise e.message.encode('UTF-8', @connection.encoding)`
`        end`

Thanks!

**Comment by FabioMR** [comment]
Hi, unfortunately we don't have support for migrations yet. Sorry.

**Comment by FabioMR** [comment]
@luisfoxi I've just released a new version (1.0.5) with migration support!
