### ISSUE TITLE
Pagination (FIRST, SKIP) does not work in Rails 5

### ISSUE THREAD

**Issue by vipantonio** [FabioMR/firebird_adapter#6]
When using this adapter with Rails 5 and trying to get

`Clients.second`

it always returns first model item.

**Comment by FabioMR** [comment]
Fixed!

**Comment by vipantonio** [comment]
I haven't tested it yet, but I guess pagination still will not work as expected with this fix.

take a look at my fix: https://github.com/vipantonio/firebird_adapter/commit/592f63dccdc240cdcb0edc847743e47ba35d95be#diff-afa6a9223051e88b8999ea26bdb36fbf

**Comment by FabioMR** [comment]
@vipantonio Fixed! Thanks for the trouble!
