### ISSUE TITLE
Problema para criar a tabela ar_internal_metadata

### ISSUE THREAD

**Issue by nitaigf** [FabioMR/firebird_adapter#7]
Ao tentar rodar migration pela primeira vez em um banco firebird acontece um conflito e não é criada a tabela ar_internal_metadata, pois um dos campos dessa tabela tem como nome a palavra "value" e essa palavra é reservada pelo firebird.

https://firebirdsql.org/refdocs/langrefupd25-reskeywords-full-reswords.html

https://www.reddit.com/r/rails/comments/ajm4vy/what_is_ar_internal_metadata_table_that_seems_to/

https://stackoverflow.com/questions/50410310/for-rails-is-creating-the-ar-internal-metadata-table-with-a-handwritten-migra

**Comment by FabioMR** [comment]
The problem has been fixed! I'm closing this issue!

Thanks @nitaigf
