### ISSUE TITLE
trouble on rails server

### ISSUE THREAD

**Issue by guilhermemvo** [FabioMR/firebird_adapter#8]
On rails server command I have the follow error:

`symbol lookup error: /home/guilhermemvo/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/fb-0.9.0/fb.so: undefined symbol: isc_attach_database`

I'm using Fedora 27, ruby 2.5.0 and rails 5.2.2.1 and in my gem list:

``` 
...
fb (0.9.0)
fb_adapter (0.6.2)
...
```

any clue?

**Comment by FabioMR** [comment]
@guilhermemvo I've just released a new version. Could you test if the error still happing please?
