### ISSUE TITLE
BigDecimal Warning

### ISSUE THREAD

**Issue by rollyar** [FabioMR/firebird_adapter#9]
Hello!! I have a BigDecimal warning, how quit that.
Ruby 2.6
Rails 5.2

Thanks!!!

**Comment by FabioMR** [comment]
Can you give an example?

**Comment by rollyar** [comment]
Sorry for the delay in the answer, this is the warning. 

/home/master/apps/aspurc/shared/bundle/ruby/2.6.0/gems/firebird_adapter-1.0.6/lib/active_record/connection_adapters/firebird/database_statements.rb:38: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.

Thank you very much for taking care of the problem.

Salu2, Rolando.

**Comment by FabioMR** [comment]
Hello @rollyar, It's a problem of the "fb" gem. They already have a pull request about it, as you can see here:
https://github.com/rowland/fb/pull/69

As soon as they fix it I release a new version.

Thanks!
